Refactoring
a-shirokov-exceed/departments-client pull request #8
Opened 2021-11-22 12:51 UTC by a-shirokov-exceed

2021-11-23 16:26 UTC, s-bodnaruk requested changes
Please, see my comments

2021-11-23 16:26 UTC, stan-velma commented on src/App.jsx
>  import "./App.scss";
Please, add empty line before importing styles

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
> +import "./mainContainer.scss";
Please, add empty line before importing styles

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
> +  const [employee, setEmployee] = useState([]); //  if i need to render all employees
Remove comment

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
> +    //  get all employee if it needed
Remove comment. Please, try not to push code with comments into the repository

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
>    const okHandler = (entityObject) => {
Rename oKHandler to understand what this function does.

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
>      const closeModal = () => {
If you run "closeModal" function once you have no need to declare it.

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
>                setDepartments(editedDepartments);
Can we use switch-case syntax to rewrite all this block? (Optional)

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
>    const deleteEntity = (objectForDelete, indexOfDelete, idOfDelete) => {
Can we rename the arguments to clarify theirs meanings? For example instead of idOfDelete use departmentId.

2021-11-23 16:26 UTC, stan-velma commented on src/components/mainContainer/mainContainer.jsx
> +          return setSnackbarOpen(true);
Why do we need return here?

2021-11-23 16:26 UTC, s-bodnaruk commented on src/components/modalAddEdit/modalAddEdit.jsx
> +      // onError={errors => console.log(errors)}
Do we need this code?

2021-11-23 16:26 UTC, s-bodnaruk commented on src/components/renderEntity/renderEntity.jsx
>          });
Remove console.log, add notification

2021-11-23 16:26 UTC, s-bodnaruk commented on src/components/renderEntity/renderEntity.jsx
>    };
Please, use camelCase. departmentId instead of departmentID

2021-11-23 16:26 UTC, s-bodnaruk commented on src/components/renderEntity/renderEntity.jsx
>                    deleteEntity(item, index, item._id);
If you have an item, why sent item._id too??

2021-11-23 16:26 UTC, s-bodnaruk commented on src/components/sidebar/sideBar.jsx
>        {/* <Link to="/employee/all">Employee</Link> */}
Remove the comment

2021-11-23 16:26 UTC, s-bodnaruk commented on src/components/userTextField/userTextField.jsx
>      //   // required={true}
Please, remove the comments

2021-11-25 08:19 UTC, a-shirokov-exceed commented on src/App.jsx
>  import "./App.scss";
Fixed

2021-11-25 08:19 UTC, a-shirokov-exceed commented on src/components/mainContainer/mainContainer.jsx
> +import "./mainContainer.scss";
Fixed

2021-11-25 08:20 UTC, a-shirokov-exceed commented on src/components/mainContainer/mainContainer.jsx
> +  const [employee, setEmployee] = useState([]); //  if i need to render all employees
Fixed

2021-11-25 08:20 UTC, a-shirokov-exceed commented on src/components/mainContainer/mainContainer.jsx
> +    //  get all employee if it needed
Fixed

2021-11-25 11:25 UTC, merged